import DashboardShell from "../../components/layout/DashboardShell";
import PageHeader from "../../components/layout/PageHeader";
import Loader from "../../components/common/Loader";
import ErrorBanner from "../../components/common/ErrorBanner";
import EmptyState from "../../components/common/EmptyState";
import StatusBadge from "../../components/common/StatusBadge";
import { useFetch } from "../../hooks/useFetch";
import * as studentApi from "../../api/student.api";
export default function CounselingHistory() {
  const { data:records,isLoading,error }=useFetch(studentApi.getCounselingHistory,r=>r.data.data.records,[]);
  return(<DashboardShell pageTitle="Counseling History"><PageHeader title="Your Counseling History" description="Only sessions your mentor marked as visible to you are shown." />{isLoading&&<Loader />}{error&&<ErrorBanner message={error} />}{records?.length===0&&<EmptyState title="No counseling records yet" />}<div className="space-y-4">{records?.map((r,i)=>(<div key={i} className="card p-5"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-ink">{new Date(r.scheduledDate).toLocaleDateString("en-IN",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</p><p className="text-xs text-muted mt-0.5">Mentor: {r.mentorName} · <span className="capitalize">{r.topic}</span></p></div><StatusBadge status={r.record?.attendance||"absent"} /></div>{r.record?.attendance==="present"&&(<div className="mt-3 space-y-2">{r.record.purpose&&<div className="rounded-md bg-paper border border-line p-3"><p className="text-xs text-muted mb-1">Purpose</p><p className="text-sm">{r.record.purpose}</p></div>}{r.record.remarks&&<div className="rounded-md bg-paper border border-line p-3"><p className="text-xs text-muted mb-1">Remarks</p><p className="text-sm">{r.record.remarks}</p></div>}{r.record.outcome&&<div className="rounded-md bg-accent-soft p-3"><p className="text-xs text-muted mb-1">Outcome</p><p className="text-sm">{r.record.outcome}</p></div>}{r.record.actionItems&&<div className="rounded-md bg-mentor-soft p-3"><p className="text-xs text-muted mb-1">Action Items</p><p className="text-sm">{r.record.actionItems}</p></div>}</div>)}</div>))}</div></DashboardShell>);
}