import axiosInstance from "./axiosInstance";
export const getDashboard = () => axiosInstance.get("/mentor/dashboard");
export const listMyStudents = (params={}) => axiosInstance.get("/mentor/students", { params });
export const getStudentsForSession = (year) => axiosInstance.get("/mentor/students/year/" + year + "/for-session");
export const createOrUpdateSession = (data) => axiosInstance.post("/mentor/sessions", data);
export const listSessions = (params={}) => axiosInstance.get("/mentor/sessions", { params });
export const getSessionById = (id) => axiosInstance.get("/mentor/sessions/" + id);
export const submitSession = (id) => axiosInstance.post("/mentor/sessions/" + id + "/submit");
export const sendMessage = (receiverId, content) => axiosInstance.post("/mentor/messages", { receiverId, content });
export const sendGroupMessage = (year, content) => axiosInstance.post("/mentor/messages/group", { year, content });
export const getConversation = (studentId) => axiosInstance.get("/mentor/messages/" + studentId);
export const listConcerns = (params={}) => axiosInstance.get("/mentor/concerns", { params });
export const respondToConcern = (id, data) => axiosInstance.patch("/mentor/concerns/" + id, data);
export const generateWeeklyReport = (data) => axiosInstance.post("/mentor/reports/weekly", data);
export const listReports = () => axiosInstance.get("/mentor/reports");