import { useState } from "react";
import DashboardShell from "../../components/layout/DashboardShell";
import PageHeader from "../../components/layout/PageHeader";
import Button from "../../components/common/Button";
import Input from "../../components/common/Input";
import Loader from "../../components/common/Loader";
import ErrorBanner from "../../components/common/ErrorBanner";
import EmptyState from "../../components/common/EmptyState";
import Modal from "../../components/common/Modal";
import { useFetch } from "../../hooks/useFetch";
import { useToast } from "../../components/common/Toast";
import * as mentorApi from "../../api/mentor.api";
function defaultRange(){const end=new Date();const start=new Date(end-7*24*60*60*1000);return{weekStartDate:start.toISOString().slice(0,10),weekEndDate:end.toISOString().slice(0,10)};}
export default function MentorReports() {
  const { showToast }=useToast(); const { data:reports,isLoading,error,refetch }=useFetch(mentorApi.listReports,r=>r.data.data.reports,[]);
  const [isFormOpen,setIsFormOpen]=useState(false); const [form,setForm]=useState({...defaultRange(),highlights:""}); const [isGenerating,setIsGenerating]=useState(false); const [formError,setFormError]=useState(""); const [expanded,setExpanded]=useState(null);
  const handleGenerate=async e=>{e.preventDefault();setFormError("");setIsGenerating(true);try{await mentorApi.generateWeeklyReport(form);showToast("Report generated.");setIsFormOpen(false);refetch();}catch(err){setFormError(err.response?.data?.message||"Failed.");}finally{setIsGenerating(false);}};
  return(<DashboardShell pageTitle="Reports"><PageHeader title="Weekly Reports" action={<Button onClick={()=>setIsFormOpen(true)}>Generate Report</Button>} />{isLoading&&<Loader />}{error&&<ErrorBanner message={error} />}{reports?.length===0&&<EmptyState title="No reports yet" />}<div className="space-y-4">{reports?.map(r=>(<div key={r._id} className="card"><div className="flex items-center justify-between px-5 py-4 border-b border-line"><div><p className="text-sm font-semibold text-ink">{new Date(r.weekStartDate).toLocaleDateString()} – {new Date(r.weekEndDate).toLocaleDateString()}</p><p className="text-xs text-muted mt-0.5">{r.totalSessionsHeld} sessions · {r.totalStudentsCounseled} students counseled</p></div><button onClick={()=>setExpanded(expanded===r._id?null:r._id)} className="text-xs text-mentor hover:underline">{expanded===r._id?"Hide":"Details"}</button></div>{expanded===r._id&&(<div className="px-5 py-4"><div className="grid grid-cols-3 gap-4 mb-4 text-center"><div className="rounded-md bg-accent-soft p-3"><p className="text-xs text-muted">Present</p><p className="text-2xl font-semibold text-accent-dark">{r.attendanceSummary?.present||0}</p></div><div className="rounded-md bg-warn-soft p-3"><p className="text-xs text-muted">Absent</p><p className="text-2xl font-semibold text-warn">{r.attendanceSummary?.absent||0}</p></div><div className="rounded-md bg-paper border border-line p-3"><p className="text-xs text-muted">Excused</p><p className="text-2xl font-semibold text-ink">{r.attendanceSummary?.excused||0}</p></div></div>{r.highlights&&<div className="rounded-md bg-mentor-soft p-3"><p className="text-xs font-medium text-mentor">Highlights</p><p className="text-sm mt-1">{r.highlights}</p></div>}</div>)}</div>))}</div>
  <Modal isOpen={isFormOpen} onClose={()=>setIsFormOpen(false)} title="Generate weekly report" maxWidth="max-w-md"><form onSubmit={handleGenerate} className="space-y-4"><div className="grid grid-cols-2 gap-4"><Input label="Week start" type="date" value={form.weekStartDate} onChange={e=>setForm(p=>({...p,weekStartDate:e.target.value}))} required /><Input label="Week end" type="date" value={form.weekEndDate} onChange={e=>setForm(p=>({...p,weekEndDate:e.target.value}))} required /></div><div><label className="field-label">Highlights (optional)</label><textarea className="field-input min-h-[80px]" value={form.highlights} onChange={e=>setForm(p=>({...p,highlights:e.target.value}))} /></div>{formError&&<ErrorBanner message={formError} />}<Button type="submit" isLoading={isGenerating} className="w-full">Generate</Button></form></Modal></DashboardShell>);
}