import { useState } from "react";
import DashboardShell from "../../components/layout/DashboardShell";
import PageHeader from "../../components/layout/PageHeader";
import StatusBadge from "../../components/common/StatusBadge";
import Button from "../../components/common/Button";
import Select from "../../components/common/Select";
import Loader from "../../components/common/Loader";
import ErrorBanner from "../../components/common/ErrorBanner";
import EmptyState from "../../components/common/EmptyState";
import Modal from "../../components/common/Modal";
import { useFetch } from "../../hooks/useFetch";
import { useToast } from "../../components/common/Toast";
import * as mentorApi from "../../api/mentor.api";
const YEAR_OPTS=[{value:"",label:"All years"},{value:"1",label:"Year 1"},{value:"2",label:"Year 2"},{value:"3",label:"Year 3"},{value:"4",label:"Year 4"}];
export default function SessionList() {
  const { showToast }=useToast(); const [yearFilter,setYearFilter]=useState(""); const [selected,setSelected]=useState(null); const [isSubmitting,setIsSubmitting]=useState(false);
  const { data:sessions,isLoading,error,refetch }=useFetch(()=>mentorApi.listSessions(yearFilter?{year:yearFilter}:{}),r=>r.data.data.sessions,[yearFilter]);
  const handleSubmit=async id=>{setIsSubmitting(true);try{await mentorApi.submitSession(id);showToast("Submitted to admin.");refetch();setSelected(null);}catch(err){showToast(err.response?.data?.message||"Failed.","error");}finally{setIsSubmitting(false);}};
  return(<DashboardShell pageTitle="Sessions"><PageHeader title="Counseling Sessions" action={<div className="flex gap-2"><Select placeholder="All years" options={YEAR_OPTS} value={yearFilter} onChange={e=>setYearFilter(e.target.value)} className="w-36" /><Button onClick={()=>window.location.href="/mentor/sessions/new"}>Record Session</Button></div>} />{isLoading&&<Loader />}{error&&<ErrorBanner message={error} />}{sessions?.length===0&&<EmptyState title="No sessions yet" description="Click Record Session to get started." />}<div className="space-y-4">{sessions?.map(s=>(<div key={s._id} className="card p-5"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 flex-wrap"><p className="text-sm font-semibold text-ink">{new Date(s.scheduledDate).toLocaleDateString("en-IN",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}</p><span className="badge bg-mentor-soft text-mentor">Year {s.year}</span><span className="badge bg-paper border border-line text-muted capitalize">{s.topic}</span><StatusBadge status={s.status} /></div><p className="text-xs text-muted mt-1">{s.presentCount} present · {s.absentCount} absent · {s.totalStudents} total</p></div><div className="flex gap-2"><button onClick={()=>setSelected(s)} className="text-xs text-mentor hover:underline">View</button>{s.status==="draft"&&<button onClick={()=>handleSubmit(s._id)} className="text-xs text-accent hover:underline">Submit</button>}</div></div></div>))}</div>
  <Modal isOpen={!!selected} onClose={()=>setSelected(null)} title={"Session — "+(selected?new Date(selected.scheduledDate).toLocaleDateString():"")} maxWidth="max-w-2xl">
    {selected&&(<div className="space-y-4"><div className="grid grid-cols-3 gap-4 text-sm"><div><p className="text-muted">Year</p><p className="font-medium">Year {selected.year}</p></div><div><p className="text-muted">Topic</p><p className="font-medium capitalize">{selected.topic}</p></div><div><p className="text-muted">Status</p><StatusBadge status={selected.status} /></div></div>{selected.generalNotes&&<div className="rounded-md bg-paper border border-line p-3"><p className="text-xs text-muted mb-1">General notes</p><p className="text-sm">{selected.generalNotes}</p></div>}<table className="w-full text-sm"><thead><tr className="border-b border-line text-left"><th className="pb-2 text-muted font-medium">Student</th><th className="pb-2 text-muted font-medium">Attendance</th><th className="pb-2 text-muted font-medium">Remarks</th><th className="pb-2 text-muted font-medium">Action Items</th></tr></thead><tbody className="divide-y divide-line">{(selected.studentRecords||[]).map(r=>(<tr key={r._id}><td className="py-2">{r.studentName}<br/><span className="text-xs text-muted">{r.studentRollNumber}</span></td><td className="py-2"><StatusBadge status={r.attendance} /></td><td className="py-2 text-muted text-xs max-w-[200px]">{r.remarks||"—"}</td><td className="py-2 text-muted text-xs max-w-[200px]">{r.actionItems||"—"}</td></tr>))}</tbody></table>{selected.status==="draft"&&<Button className="w-full" isLoading={isSubmitting} onClick={()=>handleSubmit(selected._id)}>Submit to admin</Button>}</div>)}
  </Modal></DashboardShell>);
}